TemplateTest1/TemplateTest1/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TemplateTest1.Controllers
{
    public class ArticleController : Controller
    {
        //
        // GET: /Article/

        public ActionResult Recent()
        {
            var model = new TemplateTest1.Models.RecentDateModel();
            return View(model);
        }
        }

   }

TemplateTest1/TemplateTest1/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TemplateTest1.Controllers
{
    public class CommentController : Controller
    {
        //
        // GET: /Comment/

        public ActionResult Recent()
        {
            var model = new TemplateTest1.Models.RecentDateModel();
            return View(model);
        }

    }
}

TemplateTest1/TemplateTest1/Views/Shared/RecentComments.cshtml
@{
    Layout = null;
}
@model TemplateTest1.Models.RecentDateModel
<div class="posts-wrap color">
    <h3>Recent Comments</h3>
    <ul>
        @foreach (var item in Model.Items)
        {
            <li>
                <p class="date">@item.Date.ToString("D")<span>@item.Date.ToString("hh:mm")</span></p>
                <p class="post"><a href="@item.URL">@item.text</a></p>
            </li>
        }
    </ul>
</div>
    

TemplateTest1/TemplateTest1/Views/Shared/RecentPosts.cshtml
@{
    Layout = null;
}
@model  TemplateTest1.Models.RecentDateModel
<div class="posts-wrap">
    <h3>Recent Posts</h3>
    <ul>
        @foreach (var item in Model.Items)
        {
            <li>
                <p class="date">@item.Date.ToString("D")</p>
                <p class="post"><a href="@item.URL">@item.text</a></p>
            </li>
        }
    </ul>
</div>

TemplateTest1/TemplateTest1/Views/Shared/_Layout.cshtml
<!doctype html>

<head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="~/Content/css/reset.css">
    <link rel="stylesheet" href="~/Content/css/style.css">
</head>

<body>
    <div class="wrap">
        <div class="left-column">
            <div class="wrap-avatar">
                <img src="~/Content/images/avatarIlya.png" alt="" />
                <h2>Котиков Илья Вячеславович</h2>
                <h3>студент гр.213501</h3>
            </div>
            @*<div class="menu">
                <ul>
                    <li><a href="#">Latest Post</a></li>
                    <li><a href="#">Archive</a></li>
                    <li><a href="#">About Me</a></li>
                </ul>
            </div>*@
            @*<div class="search-form">
                <input type="text" />
                <button></button>
            </div>*@
            @Html.Action("Recent", "Article")
            @Html.Action("Recent","Comment")
           </div>
        <div class="right-column">
            @RenderBody()
        </div>
    </div>
</body>
</html>